name: Update Auto-README

on:
        push:
                branches: [main]
        schedule:
                # Runs every hour
                - cron: "0 * * * *"
        workflow_dispatch: # Allows manual triggering

jobs:
        build:
                runs-on: ubuntu-latest
                permissions:
                        contents: write

                steps:
                        - name: Checkout Repository
                          uses: actions/checkout@v4

                        - name: Setup Bun
                          uses: oven-sh/setup-bun@v2
                          with:
                                  bun-version: latest

                        - name: Install Dependencies
                          run: bun install --frozen-lockfile

                        - name: Generate Content
                          run: bun run index.ts

                        - name: Commit and Push Changes
                          uses: stefanzweifel/git-auto-commit-action@v5
                          with:
                                  commit_message: "chore: updated music activity in README"
                                  # Ensure this matches the filename your index.ts is writing to
                                  file_pattern: "index.md"
                                  repository: .
